# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactorKit-Rx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactorKit'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'

  # Pods for ReactorKit-Rx

end
